import { chromium } from 'playwright-core';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

const url = process.env.TEST_URL || 'http://127.0.0.1:3000';
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', headless: true, args: ['--enable-webgl', '--ignore-gpu-blocklist', '--enable-unsafe-swiftshader', '--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream'] });
await mkdir('artifacts', { recursive: true });
const errors = [];
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
const page = await context.newPage();
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
try {
  await page.goto(url, { waitUntil: 'networkidle', timeout: 60000 });
  await page.locator('#lobby').waitFor({ state: 'visible', timeout: 30000 });
  assert.equal(await page.locator('.legal-nav a[href="/privacy.html"]').count(), 1);
  assert.equal(await page.locator('.legal-nav a[href="/terms.html"]').count(), 1);
  const legalPage = await context.newPage();
  await legalPage.goto(`${url}/privacy.html`, { waitUntil: 'networkidle' });
  assert.equal(await legalPage.locator('h1').textContent(), 'Privacy notice');
  await legalPage.goto(`${url}/terms.html`, { waitUntil: 'networkidle' });
  assert.equal(await legalPage.locator('h1').textContent(), 'Terms of use');
  await legalPage.close();
  await page.waitForTimeout(1500);
  const preview = await page.locator('#menu-preview').evaluate(video => ({ ready: video.readyState, time: video.currentTime, muted: video.muted }));
  assert.ok(preview.ready >= 2 && preview.time > 0 && preview.muted, `Lobby gameplay preview should autoplay muted: ${JSON.stringify(preview)}`);
  await page.screenshot({ path: 'artifacts/lobby.png' });
  await page.locator('#field-guide-open').click();
  await page.locator('#field-guide').waitFor({ state: 'visible' });
  await page.locator('#guide-close').click();
  await page.locator('#callsign').fill('PLAYTEST');
  await page.locator('#crew-size').selectOption('5');
  await page.locator('#deploy').click();
  await page.locator('#hud').waitFor({ state: 'visible', timeout: 15000 });
  await page.waitForFunction(() => window.__BLACKGRID__.diagnostics.networkCodec === 'gzip', undefined, { timeout: 15000 });
  await page.waitForTimeout(3000);
  const initial = await page.evaluate(() => window.__BLACKGRID__.diagnostics);
  assert.equal(initial.connected, true); assert.equal(initial.crew, 5); assert.ok(initial.zombies > 0);
  await page.mouse.move(1080, 450); await page.waitForTimeout(200);
  const beforeMove = await page.evaluate(() => window.__BLACKGRID__.diagnostics);
  await page.keyboard.down('KeyW'); await page.waitForTimeout(900); await page.keyboard.up('KeyW');
  const afterMove = await page.evaluate(() => window.__BLACKGRID__.diagnostics);
  assert.ok(afterMove.x > beforeMove.x + 0.5, `W should move toward the cursor on the right: ${beforeMove.x} -> ${afterMove.x}`);
  await page.waitForTimeout(700);
  const settledMove = await page.evaluate(() => window.__BLACKGRID__.diagnostics);
  assert.ok(Math.hypot(settledMove.x - afterMove.x, settledMove.z - afterMove.z) < 0.25,
    `Player should stop shortly after W is released: ${JSON.stringify({ released: { x: afterMove.x, z: afterMove.z }, settled: { x: settledMove.x, z: settledMove.z } })}`);
  await page.keyboard.press('KeyV');
  await page.waitForFunction(() => window.__BLACKGRID__.diagnostics.view === 'first');
  await page.waitForTimeout(200);
  assert.equal(await page.locator('#view-toggle').textContent(), 'VIEW: FIRST · V');
  await page.screenshot({ path: 'artifacts/first-person.png' });
  await page.locator('#view-toggle').click();
  await page.waitForFunction(() => window.__BLACKGRID__.diagnostics.view === 'third');
  await page.keyboard.press('KeyF');
  await page.mouse.move(1080, 450);
  await page.mouse.down(); await page.waitForTimeout(600); await page.mouse.up();
  await page.waitForFunction(() => Number(document.getElementById('ammo-number').textContent) < 12, undefined, { timeout: 10000 });
  assert.ok(Number(await page.locator('#ammo-number').textContent()) < 12);
  await page.keyboard.press('KeyR'); await page.waitForTimeout(1500);
  await page.screenshot({ path: 'artifacts/gameplay.png' });
  const second = await context.newPage();
  second.on('pageerror', error => errors.push(error.message));
  await second.goto(`${url}/?room=${initial.room}`, { waitUntil: 'networkidle' });
  await second.locator('#callsign').fill('TEAMMATE');
  await second.locator('#join-form button').click();
  await second.locator('#hud').waitFor({ state: 'visible', timeout: 15000 });
  await page.waitForTimeout(700);
  assert.equal((await page.evaluate(() => window.__BLACKGRID__.diagnostics)).humans, 2);
  assert.equal((await second.evaluate(() => window.__BLACKGRID__.diagnostics)).room, initial.room);
  const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
  await mobileContext.grantPermissions(['microphone'], { origin: url });
  const mobile = await mobileContext.newPage();
  mobile.on('pageerror', error => errors.push(error.message));
  mobile.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await mobile.goto(`${url}/?room=${initial.room}`, { waitUntil: 'networkidle' });
  await mobile.locator('#callsign').fill('MOBILE');
  await mobile.locator('#join-form button').click();
  await mobile.locator('#orientation-gate').waitFor({ state: 'visible' });
  await mobile.setViewportSize({ width: 844, height: 390 });
  await mobile.locator('#orientation-gate').waitFor({ state: 'hidden' });
  await mobile.locator('#hud').waitFor({ state: 'visible', timeout: 15000 });
  await mobile.waitForFunction(() => window.__BLACKGRID__.diagnostics.networkCodec === 'gzip');
  await page.locator('#comms-open').click(); await page.locator('#social-panel').waitFor({ state: 'visible' });
  await page.locator('#chat-input').fill('Ops channel check'); await page.locator('#chat-form button').click();
  await second.locator('#comms-open').click();
  await second.getByText('Ops channel check').waitFor({ state: 'visible' });
  await context.grantPermissions(['microphone'], { origin: url });
  await page.locator('#mic-toggle').click(); await mobile.locator('#mic-toggle').click();
  await page.waitForFunction(() => document.getElementById('mic-toggle').getAttribute('aria-pressed') === 'true', undefined, { timeout: 5000 });
  await mobile.waitForFunction(() => document.getElementById('mic-toggle').getAttribute('aria-pressed') === 'true', undefined, { timeout: 5000 });
  await page.waitForFunction(() => /VOICE CONNECTED/.test(document.getElementById('voice-status').textContent), undefined, { timeout: 15000 });
  assert.equal(await mobile.locator('#touch-controls').evaluate(el => getComputedStyle(el).display !== 'none'), true);
  const mobileBefore = await mobile.evaluate(() => window.__BLACKGRID__.diagnostics);
  const stick = await mobile.locator('#move-stick').boundingBox();
  await mobile.mouse.move(stick.x + stick.width / 2, stick.y + stick.height / 2);
  await mobile.mouse.down(); await mobile.mouse.move(stick.x + stick.width / 2 + 36, stick.y + stick.height / 2, { steps: 3 });
  await mobile.waitForTimeout(800); await mobile.mouse.up();
  const mobileAfter = await mobile.evaluate(() => window.__BLACKGRID__.diagnostics);
  assert.ok(Math.hypot(mobileAfter.x - mobileBefore.x, mobileAfter.z - mobileBefore.z) > 0.5, `Touch joystick should move a player in the shared room: ${JSON.stringify({ before: mobileBefore, after: mobileAfter, bounds: stick })}`);
  const aimBefore = mobileAfter.yaw, aimPad = await mobile.locator('#look-pad').boundingBox();
  await mobile.mouse.move(aimPad.x + aimPad.width / 2, aimPad.y + aimPad.height / 2);
  await mobile.mouse.down(); await mobile.mouse.move(aimPad.x + aimPad.width / 2 + 30, aimPad.y + aimPad.height / 2, { steps: 3 });
  await mobile.waitForTimeout(250); await mobile.mouse.up();
  const aimAfter = await mobile.evaluate(() => window.__BLACKGRID__.diagnostics.yaw);
  assert.ok(Math.abs(Math.atan2(Math.sin(aimAfter - aimBefore), Math.cos(aimAfter - aimBefore))) > 0.04, `Touch aim pad should turn the player: ${aimBefore} -> ${aimAfter} (${aimPad.x},${aimPad.y})`);
  await mobile.locator('#touch-fire').tap();
  await mobile.waitForFunction(() => Number(document.getElementById('ammo-number').textContent) < 12);
  await mobile.waitForTimeout(800);
  const touchFireState = await mobile.evaluate(() => window.__BLACKGRID__.diagnostics);
  assert.ok(Number(await mobile.locator('#ammo-number').textContent()) > 0, `Touch fire should stop firing when released: ${JSON.stringify(touchFireState)}`);
  await mobile.getByRole('button', { name: 'Toggle flashlight' }).tap();
  await mobile.waitForFunction(() => window.__BLACKGRID__.diagnostics.light === true);
  await mobile.locator('#view-toggle').tap();
  await mobile.waitForFunction(() => window.__BLACKGRID__.diagnostics.view === 'first');
  await mobile.screenshot({ path: 'artifacts/mobile-gameplay.png' });
  assert.equal((await mobile.evaluate(() => window.__BLACKGRID__.diagnostics)).humans, 3, 'Desktop and mobile browsers should share the same room');
  assert.equal((await mobile.evaluate(() => window.__BLACKGRID__.diagnostics)).nameTags, 3, 'Visible name tags should be rendered for each real player');
  await page.waitForFunction(() => document.getElementById('online-count').textContent === '3 ONLINE', undefined, { timeout: 8000 });
  assert.equal(await page.locator('#hud-online-count').textContent(), '3 ONLINE', 'The shared online counter should include all connected human players');
  await mobileContext.close();
  await page.bringToFront();
  await page.keyboard.press('KeyM');
  await page.screenshot({ path: 'artifacts/tactical-map.png' });
  await page.keyboard.press('KeyM');
  await page.keyboard.press('Escape');
  await page.locator('#ingame-settings').click();
  await page.locator('#quality').selectOption('high'); await page.locator('#settings-close').click();
  await page.waitForTimeout(1800); await page.screenshot({ path: 'artifacts/cinematic.png' });
  await page.keyboard.press('Escape'); await page.locator('#leave').click();
  await page.locator('#lobby').waitFor({ state: 'visible' });
  assert.deepEqual(errors, [], `Browser errors: ${errors.join('\n')}`);
  console.log(JSON.stringify({ result: 'PASS', diagnostics: initial, crossPlatformHumans: 3, browserErrors: errors, screenshots: ['lobby.png', 'gameplay.png', 'first-person.png', 'mobile-gameplay.png', 'tactical-map.png', 'cinematic.png'] }, null, 2));
} finally { await browser.close(); }
